# Generated by Django 6.0.7 on 2026-09-05 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_master', '0001_initial'),
        ('finance', '0005_alter_bill_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='apartment_master.flat'),
        ),
    ]
